### ISSUE TITLE
Cannot active account

### ISSUE THREAD

**Issue by ghost** [OPERANDOH2020/PlusPrivacy#74]
It said "Multiple users with email ****@gmail.com". I didn't receive the email. This is the first time I use this email address to create PlusPrivacy account. 
![image](https://user-images.githubusercontent.com/40070347/43996448-6166a40c-9df5-11e8-8906-6f899083e7c1.png)

**Comment by ghost** [comment]
You may want to know I can reset the password. But I cannot active this account.

**Comment by Mastaleru** [comment]
Hello there,

We indeed found a problem in our authentication system. 
Thank you for reporting it to us.

Also we want to inform you that now you should be able to use our services.

Thank you,

Development Team of PlusPrivacy
